### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by pbrisbin** [joshlk/jenkins-githubaction#4]
From our build logs:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I'm not sure the recommended approach for a python action. In Javascript the `@actions/core` library handles it. I guess you can just do the python equivalent of,

```sh
echo "{name}={value}" >> $GITHUB_INPUT
```

**Comment by MTJB** [comment]
Hey @joshlk, do you accept contributions? I'm happy to give this a go!

**Comment by joshlk** [comment]
Yes sure - that would be very helpful :)
